# iOS CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/ios-migrating-from-1-2/ for more details
#
---
version: 2
jobs:
  rocketjump:
    macos:
        xcode: "10.0.0"
    working_directory: ~/Waves/iOS
    environment:
      FL_OUTPUT_DIR: ~/Waves/iOS/Output
      FASTLANE_LANE: waves_test
    shell: /bin/bash --login -o pipefail
    steps:
      - add_ssh_keys:
          fingerprints:            
            - "43:eb:59:d6:49:f1:ae:81:cb:5a:ba:b8:01:64:19:39"
      - checkout
      - run:
          name: SSH
          command: ls -la ~/.ssh/
      - run:
          name: SSH Cat id_rsa_43eb59d649f1ae81cb5abab801641939
          command: cat ~/.ssh/id_rsa_43eb59d649f1ae81cb5abab801641939
      - run:
          name: SSH Cat authorized_keys
          command: cat ~/.ssh/authorized_keys
      - run:
          name: SSH Cat config
          command: cat ~/.ssh/config
      - run:
          name: Bundle
          command: bundle install
      - run: 
          name: Secure
          command: security find-identity -v -p codesigning
      - run:
          name: Fastlane
          command: bundle exec fastlane certificates
      - run:
          name: Fastlane certificates
          command: bundle exec fastlane certificates --verbose
      - run: 
          name: Secure
          command: security find-identity -v -p codesigning
      - run:
          name: Fastlane Build
          command: bundle exec fastlane $FASTLANE_LANE
      - store_artifacts:
          path: ~/Waves/iOS/Output
      - store_test_results:
          path: ~/Waves/iOS/Output/Results
workflows:
  version: 2
  sakura:
    jobs:
      - rocketjump
          filters:
            branches:
               only: develop
