# iOS CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/ios-migrating-from-1-2/ for more details
#
---
version: 2
jobs:
  rocketjump:
    macos:
        xcode: "10.0.0"
    working_directory: ~/Waves/iOS
    environment:
      FL_OUTPUT_DIR: ~/Waves/iOS/Output
      FASTLANE_LANE: waves_test
    shell: /bin/bash --login -o pipefail
    steps:
      - add_ssh_keys:
          fingerprints:            
            - "f9:5e:b7:91:7b:1e:83:ea:65:be:f9:dd:93:07:38:d5"
      - checkout
      - run:
          name: SSH
          command: ls -la ~/.ssh/
      - run:
          name: SSH Cat id_rsa_f95eb7917b1e83ea65bef9dd930738d5
          command: cat ~/.ssh/id_rsa_f95eb7917b1e83ea65bef9dd930738d5
      - run:
          name: SSH Cat authorized_keys
          command: cat ~/.ssh/authorized_keys
      - run:
          name: SSH Cat config
          command: cat ~/.ssh/config
      - run:
          name: Bundle
          command: bundle install
      - run:
          name: Fastlane
          command: bundle exec fastlane certificates
      - run:
          name: Fastlane 2
          command: bundle exec fastlane $FASTLANE_LANE
      - store_artifacts:
          path: ~/Waves/iOS/Output
      - store_test_results:
          path: ~/Waves/iOS/Output/Results
workflows:
  version: 2
  sakura:
    jobs:
      - rocketjump
